title: Chaklam Silpasuwanchai
url: https://www.chaklam.com
baseurl: ""
markdown: kramdown
collections:
  articles:
    output: true
defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: post
exclude:
  - README.md
  - source-resume.tex
  - README.txt
  - README-columns.txt
