title: Chaklam Silpasuwanchai
url: "https://www.chaklam.com"
baseurl: ""

markdown: kramdown

collections:
  articles:
    output: true
    permalink: /articles/:name/

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: post

exclude:
  - README.md