- name: Conference & Professional Leadership
  entries:
  - date: Jan 2024 – Present
    role: Chair, AI and Simulation Lab
    organization: Asian Institute of Technology
  - date: Sep 2023 – Dec 2025
    role: Chair, Sustainability Positioning Task Force
    organization: Asian Institute of Technology
  - date: 2016 – 2019
    role: Vice-Secretary General
    organization: International Chinese Association of Human-Computer Interaction (ICACHI)
  - date: '2016'
    role: General Co-Chair
    organization: ACM IxAP
  - date: 2013 – 2016
    role: Technical Liaison
    organization: ACM Chinese CHI
  - date: '2014'
    role: Publicity Chair
    organization: IDHF
- name: Program Committees
  entries:
  - date: '2018'
    role: Associate Chair, Late-Breaking Work
    organization: ACM CHI
  - date: '2017'
    role: Program Committee, Video Competition
    organization: ACM Chinese CHI
  - date: '2017'
    role: Associate Chair, Provocations and Work in Progress
    organization: ACM DIS
- name: Reviewing
  entries:
  - date: Mar 2024 – Present
    role: Reviewer
    organization: ACL / ACM CHI / NeurIPS
  - date: Sep 2023 – Present
    role: Doctoral Progress Review Committee
    organization: Asian Institute of Technology
  - date: 2016 – 2019
    role: External Reviewer
    organization: ACM CHI / ACM DIS / IEEE Transactions on Human-Machine Systems
- name: Institutional & Other Service
  entries:
  - date: 2025 – present
    role: Academic Program Coordinator of Data Science and AI Program
    organization: Asian Institute of Technology
  - date: Mar 2024 – Apr 2026
    role: Faculty Relations Committee
    organization: Asian Institute of Technology
  - date: 2021 – 2024
    role: Academic Program Coordinator of Computer Science Program
    organization: Asian Institute of Technology
  - date: Jul 2021 – Jul 2023
    role: Ethics Committee
    organization: Asian Institute of Technology
  - date: '2019'
    role: Curriculum Advisor, Computer Science
    organization: Yangon University
  - date: '2019'
    role: Curriculum Development, Data Science
    organization: Stamford International University
  - date: '2019'
    role: Local Organizer, YESIST 2019
    organization: IEEE YESIST
  - date: 2012 – 2013
    role: Student Volunteer
    organization: WISS / ACM APCHI
  - date: '2010'
    role: Event Staff
    organization: Techfest iNexus Thailand
